/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2025-2030 The GoldenEraGlobal Developers
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package global.goldenera.wallet.utils;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import lombok.experimental.UtilityClass;
import lombok.extern.slf4j.Slf4j;

/**
 * Utility class to read application version from a filtered properties file
 * generated by Maven during the build process.
 * This class uses static initialization to ensure the version is loaded
 * only once when the class is first accessed, adhering to production best
 * practices.
 */
@UtilityClass
@Slf4j
public final class VersionUtil {

    private static final String VERSION_PROPERTIES_FILE = "version.properties";
    private static final String VERSION_PROPERTY_KEY = "app.version";
    private static final String UNKNOWN_VERSION = "UNKNOWN";

    private static final String APPLICATION_VERSION;

    // Static initializer block to load the version information.
    // This runs once when the class is loaded.
    static {
        Properties properties = new Properties();
        String loadedVersion = UNKNOWN_VERSION;

        // Use try-with-resources for automatic closing of the InputStream
        try (InputStream inputStream = VersionUtil.class.getClassLoader()
                .getResourceAsStream(VERSION_PROPERTIES_FILE)) {

            if (inputStream != null) {
                properties.load(inputStream);
                loadedVersion = properties.getProperty(VERSION_PROPERTY_KEY, UNKNOWN_VERSION);
            } else {
                log.error("CRITICAL: Version properties file not found: " + VERSION_PROPERTIES_FILE
                        + ". Application version will be set to '" + UNKNOWN_VERSION + "'.");
            }
        } catch (IOException e) {
            log.error("ERROR: Failed to read version properties file. " + e.getMessage());
            loadedVersion = UNKNOWN_VERSION;
        }

        APPLICATION_VERSION = loadedVersion;
    }

    /**
     * Retrieves the application version string.
     * 
     * @return The application version, or "UNKNOWN" if loading failed.
     */
    public static String getApplicationVersion() {
        return APPLICATION_VERSION;
    }
}