export { BackupPhrasePage } from './BackupPhrasePage'
export { BipCreatePage } from './BipCreatePage'
export { BipDetailPage } from './BipDetailPage'
export { CreateWalletPage } from './CreateWalletPage'
export { DashboardPage } from './DashboardPage'
export { DeleteWalletPage } from './DeleteWalletPage'
export { ImportWalletPage } from './ImportWalletPage'
export { GovernancePage } from './GovernancePage'
export { ScanQrCodePage } from './ScanQrCodePage'
export { SettingsPage } from './SettingsPage'
export { ShowPhrasePage } from './ShowPhrasePage'
export { ToggleBiometricPage } from './ToggleBiometricPage'
export { TokenDetailPage } from './TokenDetailPage'
export { WelcomePage } from './WelcomePage'

